"use strict"
var ApplicationState={defaults:function(){return{mode:"explore",invert:!1,mapLat:"48.5",mapLon:"-122.0",mapZoom:"8",mapLayer:"default",loggedIn:!1,modalLogIn:!1,modalLogOut:!1}},initial:function(e){var e=this.defaults(),t=window.location.search.slice(0).substring(1).split("&")
for(var a in t){var n=t[a].split("="),o=decodeURIComponent(n[0]),r=decodeURIComponent(n[1])
"mode"===o?e.mode=r:"invert"===o?e.invert=0!=r:"mapLat"===o?e.mapLat=r:"mapLon"===o?e.mapLon=r:"mapZoom"===o?e.mapZoom=r:"mapLayer"===o&&(e.mapLayer=r)}return e},save:function(e){var t={mode:e.mode,mapLat:e.mapLat,mapLon:e.mapLon,mapZoom:e.mapZoom}
e.invert&&(t.invert=1),"default"!=e.mapLayer&&(t.mapLayer=e.mapLayer)
var a=[]
for(var n in t)a.push(encodeURIComponent(n)+"="+encodeURIComponent(t[n]))
window.history.replaceState(null,null,"?"+a.join("&"))}},Content={}
Content.ExistingMarker=React.createClass({displayName:"ExistingMarker",render:function(){var e=this.props.info.foray.date,t=e.slice(0,4)+"-"+e.slice(4,6)+"-"+e.slice(6,8)
return React.createElement("div",{className:"dialog-body-div"},React.createElement("h3",null,this.props.info.place.name),React.createElement("p",null,this.props.info.place.notes),React.createElement("h3",null,t),React.createElement("h4",null,this.props.info.foray.name),React.createElement("h4",null,this.props.info.foray.notes))}})
var Form={}
Form.CreateMarker=React.createClass({displayName:"CreateMarker",componentDidMount:function(){this.refs.placeName&&this.refs.placeName.getDOMNode().focus()},onSave:function(e){e.preventDefault(),this.props.onSave({place:{name:React.findDOMNode(this.refs.placeName).value,notes:React.findDOMNode(this.refs.placeNotes).value},foray:{date:React.findDOMNode(this.refs.forayYear).value+React.findDOMNode(this.refs.forayMonth).value+React.findDOMNode(this.refs.forayDay).value,name:React.findDOMNode(this.refs.forayName).value,notes:React.findDOMNode(this.refs.forayNotes).value}})},numberBox:function(e,t,a,n,o){for(var r=[],i=t;a>=i;i++){var s=10>i?"0"+i:""+i
r.push(React.createElement("option",{key:"name"+s,value:s},s))}o&&o.reverse&&r.reverse()
var c=10>n?"0"+n:""+n
return React.createElement("select",{ref:e,className:"dialog-body-row-item",defaultValue:c},r)},dateBoxes:function(){var e=new Date,t=e.getFullYear()
return React.createElement("div",{className:"dialog-body-row-div"},this.numberBox("forayYear",t-200,t+1,t,{reverse:!0}),this.numberBox("forayMonth",1,12,e.getMonth()+1),this.numberBox("forayDay",1,31,e.getDate()))},render:function(){return React.createElement("div",null,React.createElement("form",{onSubmit:this.onSave},React.createElement("div",{className:"dialog-body-div"},React.createElement("input",{type:"text",ref:"placeName",placeholder:"Name of Location"}),React.createElement("textarea",{ref:"placeNotes",placeholder:"Notes about the Location"}),React.createElement("div",{style:{height:"1em"}}),this.dateBoxes(),React.createElement("input",{type:"text",ref:"forayName",placeholder:"Name of Foray"}),React.createElement("textarea",{ref:"forayNotes",placeholder:"Notes about the Foray"}),React.createElement("button",{ref:"save",type:"submit",value:"save"},"S A V E"))))}})
var Main=React.createClass({displayName:"Main",getInitialState:function(){return ApplicationState.initial()},componentWillMount:function(){this.session=Session,Session.init(this)},childContextTypes:{main:React.PropTypes.any.isRequired},getChildContext:function(){return{main:this}},render:function(){ApplicationState.save(this.state)
var e=null
return this.state.modalLogIn?e=React.createElement(Modal.LogIn,null):this.state.modalLogOut&&(e=React.createElement(Modal.LogOut,null)),React.createElement("div",{id:"main",className:this.state.invert?"inverted":""},React.createElement("div",{id:"main-content",className:e?"blurred":""},React.createElement(Menu,null),React.createElement(Map,null)),e)}}),_extends=Object.assign||function(e){for(var t=1;t<arguments.length;t++){var a=arguments[t]
for(var n in a)Object.prototype.hasOwnProperty.call(a,n)&&(e[n]=a[n])}return e},Map=React.createClass({displayName:"Map",contextTypes:{main:React.PropTypes.any.isRequired},componentDidMount:function(){this.createMap()},getInitialState:function(){return{markers:{},premarker:null}},createMap:function(e){L.Icon.Default.imagePath="css/images",this.map=L.map(this.getDOMNode(),{doubleClickZoom:!1})
var t=function(e){return L.tileLayer("http://{s}.tile.osm.org/{z}/{x}/{y}.png",{attribution:'&copy; <a href="http://osm.org/copyright">OpenStreetMap</a>'})},a=function(e){return L.tileLayer("http://{s}.tile.thunderforest.com/"+e+"/{z}/{x}/{y}.png",{attribution:'&copy; <a href="http://www.opencyclemap.org">OpenCycleMap</a>, &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'})},n=function(e){return L.tileLayer("http://otile{s}.mqcdn.com/tiles/1.0.0/{type}/{z}/{x}/{y}.{ext}",{type:"sat",ext:"jpg",attribution:'Tiles Courtesy of <a href="http://www.mapquest.com/">MapQuest</a> &mdash; Portions Courtesy NASA/JPL-Caltech and U.S. Depart. of Agriculture, Farm Service Agency',subdomains:"1234"})}
this.layers={"default":t(),sat:n(),cycle:a("cycle"),outdoors:a("outdoors"),landscape:a("landscape"),transport:a("transport")}
for(name in this.layers)this.layers[name].shortName=name
var o={OpenStreetMap:this.layers["default"],Satellite:this.layers.sat,OpenCycleMap:this.layers.cycle,Outdoors:this.layers.outdoors,Landscape:this.layers.landscape,Transport:this.layers.transport},r=this.context.main.state,i={}
L.control.layers(o,i).addTo(this.map),L.control.gps().addTo(this.map),this.layers[r.mapLayer].addTo(this.map),this.map.setView([r.mapLat,r.mapLon],r.mapZoom),this.map.on("moveend",this.onMoveEnd),this.map.on("baselayerchange",this.onBaseLayerChange),this.map.on("contextmenu",this.onContextMenu)},onMoveEnd:function(e){var t=e.target.getCenter()
this.context.main.setState({mapLat:t.lat,mapLon:t.lng,mapZoom:e.target.getZoom()})},onBaseLayerChange:function(e){this.context.main.setState({mapLayer:e.layer.shortName})},onContextMenu:function(e){var t=Geohash.encode(e.latlng.lat,e.latlng.lng,10)
this.openMarker(t)},openMarker:function(e){var t=this.state.markers[e]
t||this.createMarker(e)},createMarker:function(e){this.setState({premarker:e})},saveMarker:function(e,t){var a=Geohash.decode(e)
this.state.markers[e]={lat:a.lat,lon:a.lon,info:t},this.setState({markers:this.state.markers})},savePremarker:function(e){this.saveMarker(this.state.premarker,e),this.clearPreMarker()},clearPreMarker:function(){this.setState({premarker:null})},render:function(){var e=[]
for(var t in this.state.markers){var a=this.state.markers[t]
e.push(React.createElement(Map.Marker,_extends({key:t,map:this.map},a),React.createElement(Content.ExistingMarker,_extends({key:t+":content"},a))))}if(this.state.premarker){var t=this.state.premarker,n=Geohash.decode(t)
e.push(React.createElement(Map.Marker,{key:t,map:this.map,lat:n.lat,lon:n.lon,forceOpen:!0,onLoseFocus:this.clearPreMarker},React.createElement(Form.CreateMarker,{key:t+":form",onSave:this.savePremarker})))}return React.createElement("div",{className:"map"},e)}})
Map.Marker=React.createClass({displayName:"Marker",componentDidMount:function(){this.createMarker(this.props)},componentWillUnmount:function(){this.deleteMarker(this.props)},componentWillReceiveProps:function(e){this.props.map!==e.map?(this.deleteMarker(this.props),this.createMarker(e)):(this.props.lat!==e.lat&&(this.leafletMarker.lat=e.lat,this.leafletMarker.update()),this.props.lon!==e.lon&&(this.leafletMarker.lon=e.lon,this.leafletMarker.update()),this.props.children!==e.children&&(e.children?this.props.children?this.props.children.key!==e.children.key&&this.leafletMarker.setPopupContent(this.updatePopup(e.children)):(this.leafletMarker.bindPopup(),this.leafletMarker.setPopupContent(this.updatePopup(e.children))):this.leafletMarker.unbindPopup()),this.props.onLoseFocus!==e.onLoseFocus&&(this.props.onLoseFocus&&this.leafletMarker.off("popupclose",this.props.onLoseFocus),e.onLoseFocus&&this.leafletMarker.on("popupclose",e.onLoseFocus))),e.forceOpen&&this.leafletMarker.openPopup()},createMarker:function(e){this.leafletMarker=L.marker([this.props.lat,this.props.lon]),this.leafletMarker.addTo(e.map),e.children&&(this.leafletMarker.bindPopup(),this.updatePopup(e.children)),e.forceOpen&&this.leafletMarker.openPopup(),e.onLoseFocus&&this.leafletMarker.on("popupclose",e.onLoseFocus)},deleteMarker:function(e){this.leafletMarker&&(e.map.removeLayer(this.leafletMarker),this.leafletMarker=null)},updatePopup:function(e){var t=document.createElement("div")
React.render(React.Children.only(e),t),this.leafletMarker.setPopupContent(t)},render:function(){return null}}),L.Control.GPS=L.Control.extend({options:{position:"topleft",targetText:"⌖",targetTitle:"Geolocation"},onAdd:function(e){var t=this,a=L.DomUtil.create("div","leaflet-control-zoom leaflet-bar"),n=L.DomUtil.create("a","leaflet-control-zoom-in",a)
n.innerHTML=this.options.targetText,n.title=this.options.targetTitle,n.href="#"
var o=function(t){e.locate({setView:!0,maxZoom:16})}
L.DomEvent.on(n,"mousedown dblclick",L.DomEvent.stopPropagation).on(n,"click",L.DomEvent.stop).on(n,"click",o).on(n,"click",this._refocusOnMap)
var r=function(a){var n=a.accuracy/2
t.circle&&t.circle.removeFrom&&t.circle.removeFrom(e),t.circle=L.circle(a.latlng,n),t.circle.addTo(e)}
return e.on("locationfound",r),a}}),L.control.gps=function(e){return new L.Control.GPS(e)}
var Menu=React.createClass({displayName:"Menu",contextTypes:{main:React.PropTypes.any.isRequired},getInitialState:function(){return{drawerActive:!1,hintActive:!1}},onMouseOver:function(e){this.setState({drawerActive:!0})},onMouseOut:function(e){this.setState({drawerActive:!1})},onIconEvent:function(e,t){"click"==t.type?"inverse"==e?this.context.main.setState({invert:!this.context.main.state.invert}):"login"==e?this.context.main.setState({modalLogIn:!0}):"logout"==e?this.context.main.setState({modalLogOut:!0}):e==this.state.hint&&this.context.main.setState({mode:e}):"mouseover"==t.type?this.setState({hint:e,hintActive:!0}):"mouseout"==t.type&&this.setState({hintActive:!1})},titleMap:{forages:["F O R","A G E S"],explore:["E X P","L O R E"],research:["R E","S E A R C H"],recollect:["R E","C O L L E C T"],inverse:["I N","V E R S E"],logout:["L O G","O U T"],login:[" L O G","I N "]},prevModeMap:{explore:"research",recollect:"explore",research:"recollect"},nextModeMap:{explore:"recollect",recollect:"research",research:"explore"},render:function(){return React.createElement("div",{className:"menu",onMouseOver:this.onMouseOver,onMouseOut:this.onMouseOut},React.createElement(Menu.Title,{texts:this.titleMap.forages,active:!this.state.drawerActive}),this.render_hint(),this.render_drawer())},render_drawer:function(){var e=this.context.main.state.mode,t=this.prevModeMap[e],a=this.nextModeMap[e]
return React.createElement("div",{style:{width:"100vw",display:"flex",opacity:this.state.drawerActive?1:0,top:this.state.drawerActive?0:-100,position:"absolute",transition:"opacity 1.25s, top 0.5s"}},React.createElement(Menu.Spacer,{width:"1em"}),React.createElement(Menu.Icon,{text:"☯",name:"inverse",callback:this.onIconEvent}),React.createElement(Menu.Spacer,null),React.createElement(Menu.Icon,{text:"⚝",name:a,callback:this.onIconEvent}),React.createElement(Menu.Spacer,{width:"0.5em"}),React.createElement(Menu.Icon,{text:"⇜"}),React.createElement(Menu.Spacer,{width:"0.5em"}),React.createElement("div",{style:{flex:"0 0 auto"}},React.createElement(Menu.Title,{texts:this.titleMap[e],active:!this.state.hintActive})),React.createElement(Menu.Spacer,{width:"0.5em"}),React.createElement(Menu.Icon,{text:"⇝"}),React.createElement(Menu.Spacer,{width:"0.5em"}),React.createElement(Menu.Icon,{text:"⚝",name:t,callback:this.onIconEvent}),React.createElement(Menu.Spacer,null),this.context.main.state.loggedIn?React.createElement(Menu.Icon,{text:"Ω",name:"logout",callback:this.onIconEvent}):React.createElement(Menu.Icon,{text:"Å",name:"login",callback:this.onIconEvent}),React.createElement(Menu.Spacer,{width:"1em"}))},render_hint:function(){return React.createElement("div",{style:{width:"100vw",display:"flex",opacity:this.state.hintActive?1:0,top:this.state.hintActive?0:-100,position:"absolute",transition:"opacity 1.25s, top 0.5s"}},React.createElement("div",{style:{flex:"1 0 auto"}},React.createElement(Menu.Title,{texts:this.titleMap[this.state.hint],active:this.state.hintActive})))}})
Menu.Spacer=React.createClass({displayName:"Spacer",render:function(){return this.props.width?React.createElement("div",{style:{flex:"0 1 "+this.props.width}}):React.createElement("div",{style:{flex:"1 1 auto"}})}}),Menu.Icon=React.createClass({displayName:"Icon",callbackWrapper:function(e){e.preventDefault(),this.props.callback(this.props.name,e)},render:function(){var e=React.createElement("h2",null,React.createElement("span",{className:"ddim"},this.props.text))
return this.props.callback&&(e=React.createElement("h2",null,React.createElement("a",{href:"",onClick:this.callbackWrapper,onMouseOver:this.callbackWrapper,onMouseOut:this.callbackWrapper},this.props.text))),React.createElement("div",{style:{flex:"0 1 auto"}},e)}}),Menu.Title=React.createClass({displayName:"Title",render:function(){var e=this.props.texts||[],t=[],a=!0
for(var n in e){var o=e[n]
if(o.length>0){var r=e[n].split(" ")
for(var i in r){var s="-"+n+"-"+i
t.push(React.createElement("h2",{key:s,className:a?"dim":""},r[i]))}}a=!a}return React.createElement("div",{style:{opacity:this.props.active?1:0,transition:"opacity 1.25s",width:"100%",display:"flex",justifyContent:"center"}},React.createElement("div",{style:{width:"12em",display:"flex",justifyContent:"space-between"}},t))}})
var Modal={}
Modal.LogIn=React.createClass({displayName:"LogIn",contextTypes:{main:React.PropTypes.any.isRequired},componentDidMount:function(){document.body.addEventListener("keydown",this.onKeyDown),this.refs.username&&this.refs.username.getDOMNode().focus()},componentWillUnmount:function(){document.body.removeEventListener("keydown",this.onKeyDown)},onKeyDown:function(e){"Escape"==e.key&&this.context.main.setState({modalLogIn:!1})},onLogIn:function(e){var t=this
e.preventDefault()
var a=React.findDOMNode(this.refs.username),n=React.findDOMNode(this.refs.password)
Session.logIn(a.value,n.value,function(){t.context.main.setState({modalLogIn:!1,loggedIn:!0})},function(e){a.value="",n.value=""})},onCancel:function(e){this.context.main.setState({modalLogIn:!1})},render:function(){return React.createElement("div",{className:"modal-suspension"},React.createElement("div",{className:"dialog-box"},React.createElement("div",{className:"dialog-header-div"},React.createElement("h3",null,React.createElement("span",{className:"dim"},"L O G")," I N ",React.createElement("span",{className:"dim"},"?"))),React.createElement("form",{onSubmit:this.onLogIn},React.createElement("div",{className:"dialog-body-div"},React.createElement("input",{ref:"username",type:"text",placeholder:"U S E R N A M E",className:"modal"}),React.createElement("input",{ref:"password",type:"password",placeholder:"P A S S W O R D",className:"modal"}),React.createElement("button",{ref:"login",type:"submit",value:"login"},"          ",React.createElement("p",null,"L O G I N")),React.createElement("button",{ref:"cancel",type:"button",onClick:this.onCancel},React.createElement("p",null,"C A N C E L"))))))}}),Modal.LogOut=React.createClass({displayName:"LogOut",contextTypes:{main:React.PropTypes.any.isRequired},componentDidMount:function(){document.body.addEventListener("keydown",this.onKeyDown),this.refs.logOut&&this.refs.logOut.getDOMNode().focus()},componentWillUnmount:function(){document.body.removeEventListener("keydown",this.onKeyDown)},onKeyDown:function(e){"Escape"==e.key&&this.context.main.setState({modalLogOut:!1})},onLogOut:function(e){Session.logOut(),this.context.main.setState({modalLogOut:!1})},onCancel:function(e){this.context.main.setState({modalLogOut:!1})},render:function(){return React.createElement("div",{className:"modal-suspension"},React.createElement("div",{className:"dialog-box"},React.createElement("div",{className:"dialog-header-div"},React.createElement("h3",null,React.createElement("span",{className:"dim"},"L O G")," O U T ",React.createElement("span",{className:"dim"},"?"))),React.createElement("div",{className:"dialog-body-div"},React.createElement("button",{type:"button",ref:"logOut",onClick:this.onLogOut},React.createElement("p",null,"L O G O U T")),React.createElement("button",{type:"button",ref:"cancel",onClick:this.onCancel},React.createElement("p",null,"C A N C E L")))))}})
var Session={init:function(e){this.main=e,this.createLocalDB(),this.checkIfLoggedIn()},appName:function(){return"forages"},dbUrl:function(e){return"http://forages-db.ilvain.com:5984/"+e},dbRemote:function(e){return new PouchDB(this.dbUrl(e),{skipSetup:!0})},dbLocal:function(e){return new PouchDB(e,{skipSetup:!0})},createLocalDB:function(){var e=this.dbLocal(this.appName())
this.localDB=e,e.info()["catch"](function(e){console.error(e)})},checkIfLoggedIn:function(){var e=this,t=this.dbRemote(this.appName()+"_public")
t.getSession().then(function(a){var n=a.userCtx.name
if(n)return t.getUser(n).then(function(a){var o=e.dbRemote(a[e.appName()].dbname)
return o.getSession().then(function(a){a.userCtx.name===n&&(e.remoteDB=o,e.remotePublicDB=t,e.main.setState({loggedIn:!0}))})})})["catch"](function(e){console.error(e)})},logIn:function(e,t,a,n){var o=this,r=this.dbRemote(this.appName()+"_public")
r.logIn(e,t).then(function(n){return r.getUser(e).then(function(n){var i=o.dbRemote(n[o.appName()].dbname)
return i.logIn(e,t).then(function(e){o.remoteDB=i,o.remotePublicDB=r,o.main.setState({loggedIn:!0}),a()})})})["catch"](function(e){console.error(e),n(e)})},logOut:function(){this.remotePublicDB&&this.remotePublicDB.logOut(),this.remoteDB&&this.remoteDB.logOut(),this.remotePublicDB=null,this.remoteDB=null,this.main.setState({loggedIn:!1})}}
